// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sutxoiwtqtqvssonhpqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1dHhvaXd0cXRxdnNzb25ocHFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNjU1MjcsImV4cCI6MjA3MTg0MTUyN30.V2jfiPCd1obR6hid4C5Siw8ziprxvyoqb-FlqDBLRCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});